name: Generate Lic Key

on:
  workflow_dispatch:
    inputs:
      license_key:
        description: 'Input license key (e.g., SGPJ-7SKL)'
        required: true
      license_type:
        description: 'License type (ros or chr)'
        required: true
        default: 'ros'

permissions:
  contents: write

jobs:
  Gen_Lic_Key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Generate License
      id: generate_license
      run: |
        if [ "${{ github.event.inputs.license_type }}" = "chr" ]; then
          python3 license.py licgenchr "${{ github.event.inputs.license_key }}" "${{ secrets.CUSTOM_LICENSE_PRIVATE_KEY }}" > "${{ github.event.inputs.license_key }}.key"
        else
          python3 license.py licgenros "${{ github.event.inputs.license_key }}" "${{ secrets.CUSTOM_LICENSE_PRIVATE_KEY }}" > "${{ github.event.inputs.license_key }}.key"
        fi
        
    - name: Ensure License Keys Directory Exists
      run: |
        mkdir -p "License Keys"

    - name: Move and Commit License Key File
      run: |
        mv "${{ github.event.inputs.license_key }}.key" "License Keys/"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add "License Keys/${{ github.event.inputs.license_key }}.key"
        git commit -m "Add license key file: License Keys/${{ github.event.inputs.license_key }}.key"
        git push